services:
  flaskapp:
    build: .
    command: flask run --host=0.0.0.0 --reload
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  testing:
    build: ./sshTesting
    ports:
      - "2222:22"
    restart: unless-stopped
    profiles:
      - dev
