services:
  flaskapp:
    build: .
    command: flask run --host=0.0.0.0 --debug
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  testing:
    build: ./sshTesting
    ports:
      - "2222:22"
    restart: unless-stopped
    profiles:
      - dev

  mongo:
    image: mongo:latest
    volumes:
      - ./db-data:/data/db
    ports:
      - "27017:27017"
